apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system-source.yaml
  - gotk-components.yaml
  - gotk-sync.yaml
  - ../hellogo/deployment.yaml
  - ../hellogo/service.yaml
  - ../hellogo/kustomization.yaml
  - ../nextcloud/configmap.yaml
  - ../nextcloud/helmrelease.yaml

