apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud-repo
        namespace: flux-system
      version: "*"
  valuesFrom:
  - kind: ConfigMap
    name: nextcloud-values
    valuesKey: values.yaml

