apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: api
        image: 270489696282.dkr.ecr.us-east-1.amazonaws.com/hellogo:latest
        ports:
        - containerPort: 8080
